public enum AudioClipId
{
    BackgroundMusic = 1,
    Loading = 2,
    Popup = 3,
    DecorMusic = 10,
    ItemApply = 20,
    ItemSelect = 30,
    CoinFly = 35,
    CoinFlyUnlock = 38,
    PanelIn = 40,
    PanelOut = 50,
    ClickFailed = 60,
    BrightStart = 70,
    AddCoin = 80,
    LevelPass = 90,
    GameWin = 100,
    GameFail = 110,
    DecorComplete = 120,
    PopupOpen = 130,
    PopupClose = 140,
    DailyBonus = 150,
    Purchased = 160,
    AddGem = 170,
    AddReward = 180,
    ScrollRoomChage = 190,
    LoadingPaper = 200,
    PiggyBankCollect = 210,
    ButtonClick = 220,
    CollectLamp = 1483,
    SpinEffect = 1500,
    BingoSpinEffect = 1511,
    PutInSound = 1520,
    PickUpSound = 1530,
    PutDownSound = 1540,
    CompleteMatch3,
    GasBurn,
    IceBreaking,
    IceSmelling,
    ClickBtn,
    Notice,
    NoticeOrder,
    Clock,
    XeoXeoBep,
    ComBoUp1,
    ComboUp2,
    ComboUp3,
    ComboUp4,
    ComboUp5,
    Foil,
    NewBestCombo,
    TurnOut,
    SwapBooster,
    CommonMan,
    YaHo,
    Tada,
}